name = "NerdCavernaCraft"
author = "Arthur"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "119733b42401fd08b48353a7c912cec35a0206a28bd3700725782526920c8e31"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
