name = "NerdCavernaCraft"
author = "Arthur"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d32ad12c436d7fb1aa837b892a3cf67cfa1475b6c67934d2c4c38cf533c1cfcf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
