name = "NerdCavernaCraft"
author = "Arthur"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5952f4b80f3b9eb76e4e3a062ad96d1baf0e2ea9e72e7301ba3d0a1ecc6b607"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[options]
datapack-folder = "datapacks"
